apiVersion: v1
kind: Service
metadata:
  name: ticked
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: ticked
    tier: backend

