apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ticked
    tier: backend
    deployedBy: deploy-node-app
  name: ticked
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ticked
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ticked
        tier: backend
    spec:
      containers:
        - image: 'jusola/ticked:latest'
          imagePullPolicy: Always
          name: ticked
          env:
            - name: GET_HOSTS_FROM
              value: dns
          envFrom:
          - secretRef:
              name: secret
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 3m
              memory: 64Mi
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

