apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ticked-ingress
spec:
  rules:
  - host: server.ticked.jusola.xyz
    http:
      paths:
      - backend:
          serviceName: ticked
          servicePort: 5000
  tls:
  - hosts:
    - server.ticked.jusola.xyz
    secretName: ticked-cert