apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ticked
spec:
  rules:
  - host: server.ticked.cf
    http:
      paths:
      - backend:
          serviceName: ticked
          servicePort: 5000
  tls:
  - hosts:
    - server.ticked.cf
    secretName: ticked-cert-secret

