apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-client
    tier: backend
    deployedBy: deploy-node-app
  name: ticked
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres-client
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ticked
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: 'jusola/ticked:latest'
          imagePullPolicy: Always
          name: postgres-client
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 3m
              memory: 64Mi
          command:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

