---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongo
  spec:
    selector:
      matchLabels:
        app: mongo
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: mongo
      spec:
        containers:
          - name: master
            image: jusola/ticked-mongo:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
              limits:
                cpu: 25m
                memory: 100Mi
            ports:
              - containerPort: 27017
                name: mongo
            envFrom:
              - secretRef:
                  name: secret
            volumeMounts:
              - mountPath: /data/db
                name: mongo-data
        volumes:
          - name: mongo-data
            persistentVolumeClaim:
              claimName: mongo-pvc
    revisionHistoryLimit: 0
